const mongoose=require("mongoose");

const userSchema=mongoose.Schema({
    userName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true,
        lowercase:true,
        unique:true,
        match:/^[^\s@]+@[^\s@]+\.[^\s@]+$/
    },
    password:{
        type:String,
        required:true,
        minlength:6
    },
    token:{
        type:String,
        default:""
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    otp:{
        type:String,
        default:""
    },
    otpExpire:{
        type:Date,
        default:undefined
    },
    usersData:{
        type:Array,
        default:[]
    },
    profile:{
        name:{
            type:String,
            default:""
        },
        image:{
            type:String,
            default:""
        },
        about:{
            type:String,
            default:""
        }
    }
});
module.exports=mongoose.model("ChatUser",userSchema);